/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model(props: any) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF('/Capoeira_Abe.glb');
	const { actions, clips, mixer, names, ref } = useAnimations(
		animations,
		group
	);

	function handleKick() {
		const act = actions.kick;
		// act.repetitions = 2;
		act.clampWhenFinished = true;
		act.getClip().toJSON;
		act.play();
		console.log({ actions, clips, mixer, names, ref });
	}

	useEffect(() => {
		handleKick();
	}, []);

	return (
		<group ref={group} onClick={handleKick} {...props} dispose={null}>
			<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
				<primitive object={nodes.mixamorigHips} />
				<skinnedMesh
					geometry={(nodes as any).Ch39.geometry}
					material={materials.Ch39_Body}
					skeleton={(nodes as any).Ch39.skeleton}
					castShadow={true}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/Capoeira_Abe.glb');
