/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props: any) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/Capoeira_Abe.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          geometry={(nodes as any).Ch39.geometry}
          material={materials.Ch39_Body}
          skeleton={(nodes as any).Ch39.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Capoeira_Abe.glb");
